# Generated by Django 6.0.4 on 2026-05-02 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0002_alter_profile_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='fitness_goal',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='height',
            field=models.FloatField(blank=True, help_text='Height in CM', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='weight',
            field=models.FloatField(blank=True, help_text='Weight in KG', null=True),
        ),
    ]
