# Generated by Django 6.0.4 on 2026-05-03 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0004_profile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
